FROM ubuntu AS builder

WORKDIR /git
RUN apt update && apt install -y git && git clone https://github.com/aceberg/aceberg-bootswatch-fork.git
RUN mkdir bootswatch
RUN cp -R aceberg-bootswatch-fork/dist bootswatch/



FROM node:20-alpine
EXPOSE 8850/tcp
WORKDIR /app

RUN npm install http-server -g && \
    npm install bootstrap@5.3.2 bootstrap-icons@1.11.0
RUN apk add --no-cache bash

COPY --from=builder /git/bootswatch /app/node_modules/bootswatch

COPY node-bootstrap/download-fonts.sh /download-fonts.sh
RUN bash /download-fonts.sh /app/node_modules/bootswatch
RUN mkdir -p /app/icons

ENTRYPOINT ["http-server"]
CMD ["--cors", "-p", "8850"]
