name: atheos-ide

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'atheos-ide/**'

env:
  IMAGE_NAME: atheos-ide

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image to docker.io
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          addLatest: true
          dockerfile: ${{ env.IMAGE_NAME }}/Dockerfile 
          directory: ${{ env.IMAGE_NAME }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sync README.md to DockerHub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          readme: "./${{ env.IMAGE_NAME }}/README.md"